/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_dynamicload_jni_DynamicLoadHelper */

#ifndef _Included_com_example_dynamicload_jni_DynamicLoadHelper
#define _Included_com_example_dynamicload_jni_DynamicLoadHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_dynamicload_jni_DynamicLoadHelper
 * Method:    getSOName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_dynamicload_jni_DynamicLoadHelper_getSOName
  (JNIEnv *, jobject);

/*
 * Class:     com_example_dynamicload_jni_DynamicLoadHelper
 * Method:    plus
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_example_dynamicload_jni_DynamicLoadHelper_plus
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
